REACT_APP_BUCKET_NAME = "pabjobs08"
REACT_APP_AWS_REGION = "ap-south-1"
REACT_APP_AWS_DIR_NAME = "pabprofilenew"
REACT_APP_AWS_ACCESS_KEY_ID = AKIAQOQT46IKRCQ24JN2
REACT_APP_AWS_ACCESS_KEY_ID = 

REACT_APP_AWS_SECRET_ACCESS_KEY = c4iP9zdUYWvF4v14bn+uk0mDBGpcf/vv1gJcNTkz
REACT_APP_AWS_SECRET_ACCESS_KEY = 
